name: My test workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v5
        
        - name: Welcome Message
          run: echo "Welcome to new actions"

        - name: List all the files
          run: ls -la

        - name: README FILE
          run: cat README.md
        
        
